### PR TITLE
Authentication Files have been deleted

### LINKED ISSUE #56: Remove Auth Layers from User Service (pkg)
Remove authentication-related layers from the "pkg" layer of the User Service to organize the architecture.

### PR DESCRIPTION
**Pull request by ebrarkesici**
Closes #56 
Authentication.go and grpc.go files and related test files were deleted

### CODE REVIEW

**Comment by Sddilora** [comment]
add desc and Closes #xxx

**Comment by Sddilora** [comment]
There were also implementations in the pkg/presentation/controller/grpc/grpc.go file from an existing service. These implementations also need to be removed.

**Comment by Sddilora** [comment]
Only the implementations of the "authentication" package's (pb_authentication) method should be removed, not the entire file.

**Review by Feyzanrs — CHANGES_REQUESTED** [review]
Upon reviewing, I noticed that there are a few more files that need to be deleted. Additionally, the `grpc.go` and `grpc_test.go` files should not be completely removed; only specific functions from these files need to be removed.

**Pull request closed without merging**
