### PR TITLE
compnayId field removed

### LINKED ISSUE #64: The "companyId" field needs to be removed.
https://github.com/octoposprime/op-be-user/blob/4fe7b2391de25d0fb80c4d6517dab5913d23b8dc/internal/domain/model/entity/userfilter.go#L37

The "companyId" field needs to be removed from "NewUserFilter" func

### PR DESCRIPTION
**Pull request by arzuuddemir**
the branch name has been changed to align with standardization.
close #64

### CODE REVIEW

**Review by Sddilora — APPROVED** [review]
👍🏻 
Well done

**Comment by Sddilora** [comment]
add the other team members as reviewers ( @Feyzanrs, @Maraza25, @Smnrgcl, @ebrarkesici, @mervegonc, @johsquaree )

**Comment by Sddilora** [comment]
The statement "I have corrected what you said" is not the most effective way to describe your PR. A better description might be "the branch name has been changed to align with standardization."

**Comment by arzuuddemir** [comment]
I have made the necessary changes.

**Review by Feyzanrs — APPROVED** [review]

**Review by Smnrgcl — APPROVED** [review]

**Review by Smnrgcl — COMMENTED** [review]
:)

**Pull request merged**
